### ISSUE TITLE
Errors stop the whole app

### ISSUE THREAD

**Issue by m-pokrovskii** [Meteor-Community-Packages/meteor-postcss#3]
If something cause an error, it's stops the whole app. Only restart meteor help.

**Comment by juliancwirko** [comment]
could you provide more information ?

**Comment by m-pokrovskii** [comment]
Install simple vars plugin. Use some variable, but not define it. It drops an error, and meteor app not refreshing anymore.

**Comment by juliancwirko** [comment]
Ok I think that I should provide better PostCSS errors catching there. I'll try to fix it today.

**Comment by juliancwirko** [comment]
Ok you can update to version 0.2.4 and let me know if this help

On the server console you should now get something similar to my demo error:

``` bash
=> Modified -- restarting.                    
=> Errors prevented startup:                  

   While minifying app stylesheet:
   app/client/postcss-demo.css:14:5: postcss-simple-vars: /home/jul/workspace/meteor/postcss-demo/client/postcss-demo.css:14:5: Undefined variable $column

   Css Syntax Error.

   postcss-simple-vars: /home/jul/workspace/meteor/postcss-demo/client/postcss-demo.css:14:5: Undefined variable $column
   t: translateX(10%);
   w: $column;
   ^
   text-align: right;

=> Your application has errors. Waiting for file change.
```

Then if you fix the error it should auto restart the Meteor server.

Also on the client when the app is stopped because of this error when you refresh the site you should get the same error in the browser.

**Comment by m-pokrovskii** [comment]
It will be awesome ) thanks for your plugin.

**Comment by juliancwirko** [comment]
@m-pokrovskii hey, let me know if this helped :)
